version: 1.0.4.{build}

configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- ps: >-
    $config = @"

    {
      "slack": {
        "userAuthToken": "$env:userAuthToken",
        "botAuthToken": "$env:botAuthToken",
        "testChannel": "$env:testChannel",
        "directMessageUser": "$env:directMessageUser",
        "authCode": "$env:authCode",
        "clientId": "$env:clientId",
        "clientSecret": "$env:clientSecret"
      }
    }

    "@

    $config | Set-Content SlackAPI.Tests\Configuration\config.json

build_script:
- cmd: >-
    nuget restore -SolutionDirectory . SlackAPI

    nuget restore -SolutionDirectory . SlackAPI.Tests

    msbuild SlackAPI.sln /verbosity:minimal /logger:"%PROGRAMFILES%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration="Release"

    %xunit20%\xunit.console.x86 SlackAPI.Tests\bin\Release\SlackAPI.Tests.dll -appveyor -noshadow

    nuget pack SlackAPI.nuspec -Version %APPVEYOR_BUILD_VERSION%

    dotnet restore

    dotnet build SlackAPI SlackAPI.Tests --configuration Release

    dotnet test SlackAPI.Tests --configuration Release

    dotnet pack SlackAPI --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

    move SlackAPI\bin\Release\SlackAPI.1.0.5-%APPVEYOR_BUILD_NUMBER%.nupkg SlackAPI\bin\Release\SlackAPI-core.1.0.5-%APPVEYOR_BUILD_NUMBER%.nupkg

    move SlackAPI\bin\Release\SlackAPI.1.0.5-%APPVEYOR_BUILD_NUMBER%.symbols.nupkg SlackAPI\bin\Release\SlackAPI-core.1.0.5-%APPVEYOR_BUILD_NUMBER%.symbols.nupkg

test: off

artifacts:
- path: SlackAPI.*.nupkg
  name: SlackAPI Nuget package

- path: SlackAPI-core.*.nupkg
  name: SlackAPI .NetCore Nuget package
