version: 1.0.5.{build}
image: Visual Studio 2015

environment:
  matrix:
    - CLI_VERSION: 1.0.0-preview4-004233

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true

install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

before_build:
- ps: >-
    $config = @"

    {
      "slack": {
        "userAuthToken": "$env:userAuthToken",
        "botAuthToken": "$env:botAuthToken",
        "testChannel": "$env:testChannel",
        "directMessageUser": "$env:directMessageUser",
        "authCode": "$env:authCode",
        "clientId": "$env:clientId",
        "clientSecret": "$env:clientSecret"
      }
    }

    "@

    $config | Set-Content SlackAPI.Tests\Configuration\config.json

build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: '.\artifacts\**\*.nupkg'
  name: Nuget packages

deploy:
- provider: NuGet
  server: https://www.myget.org/F/slackapi/api/v2
  api_key:
    secure: dt+bmkFjmkMgVdDXaaqTC4IRORfSrBSEePOGaaVPkEsKs/lGxxth21bkkBqMuJqM
  # Deploy symbol package too
  skip_symbols: false
  symbol_server: https://www.myget.org/F/slackapi/symbols/api/v2/package

#- provider: NuGet
#  name: production
#  api_key:
#    secure: OVMRfHowHPun4n8cJXPNGg==
#  on:
#    branch: master
#    appveyor_repo_tag: true
