version: 1.0.4.{build}

configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- ps: >-
    $config = @"

    {
      "slack": {
        "userAuthToken": "$env:userAuthToken",
        "botAuthToken": "$env:botAuthToken",
        "testChannel": "$env:testChannel",
        "directMessageUser": "$env:directMessageUser",
        "authCode": "$env:authCode",
        "clientId": "$env:clientId",
        "clientSecret": "$env:clientSecret"
      }
    }

    "@

    $config | Set-Content SlackAPI.Tests\Configuration\config.json
- nuget restore

build_script:
- cmd: >-
    nuget restore -SolutionDirectory . SlackAPI\packages.config

    nuget restore -SolutionDirectory . SlackAPI.Tests\packages.config

    msbuild SlackAPI.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration="Release" /p:Platform="Any CPU" /p:CI_BUILD="true"

    nuget pack SlackAPI.nuspec -Version %APPVEYOR_BUILD_VERSION%

    dotnet restore

    dotnet build SlackAPI SlackAPI.Tests --configuration Release

    dotnet pack SlackAPI --configuration Release

    mv SlackAPI\bin\Release\SlackAPI.1.0.5.nupkg SlackAPI\bin\Release\SlackAPI-core.1.0.5.nupkg

    mv SlackAPI\bin\Release\SlackAPI.1.0.5.symbols.nupkg SlackAPI\bin\Release\SlackAPI-core.1.0.5.symbols.nupkg

test_script:
- cmd: >-
    vstest.console /logger:Appveyor SlackAPI.Tests\bin\Release\SlackAPI.Tests.dll

    dotnet test SlackAPI.Tests

artifacts:
- path: SlackAPI.*.nupkg
  name: SlackAPI Nuget package

- path: SlackAPI-core.*.nupkg
  name: SlackAPI .NetCore Nuget package
